### ISSUE TITLE
跟大佬学习，webpack这些配置不是太懂

### ISSUE THREAD

**Issue by pluscai** [cdswyda/toy-react#1]
![image](https://user-images.githubusercontent.com/22081597/90111213-e07c0d00-dd80-11ea-8013-6dc6681818ee.png)

**Comment by magicds** [comment]
看文档就好[https://babeljs.io/docs/en/babel-plugin-transform-react-jsx](https://babeljs.io/docs/en/babel-plugin-transform-react-jsx)，那里默认是 `React.createElement`
